branches:
  only:
  - master
language: node_js
sudo: false
node_js:
- '5'
before_install:
- openssl aes-256-cbc -K $encrypted_b5a1a1806c12_key -iv $encrypted_b5a1a1806c12_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp ssh_config ~/.ssh/config
- git config --global user.name "summeren"
- git config --global user.email "Summeren@users.noreply.github.com"
install:
- cd blog
- npm install hexo-cli -g
- npm install
- npm install hexo-generator-feed --save
- npm install hexo-generator-sitemap --save
- npm install hexo-deployer-git --save
script:
- cd blog
- hexo clean
- hexo g
- hexo d
