branches:
  only:
  - master
  
language: node_js
sudo: false
node_js:
- '4.2'

before_install:
- git config --global user.name "Winteren"
- git config --global user.email "Winteren@users.noreply.github.com"

env:
  - TZ="Asia/Shanghai"
  
install:
- cd blog
- npm install hexo-cli -g
- npm install
- npm install hexo-generator-feed --save
- npm install hexo-generator-sitemap --save
- npm install hexo-deployer-git --save

script:
- hexo clean
- hexo g
- cp CNAME public/CNAME

after_success:
- mkdir .deploy
- cd .deploy
- git clone --depth 1 --branch master --single-branch $DEPLOY_REPO . || (git init && git remote add -t master origin $DEPLOY_REPO)
- rm -rf ./*
- cp -r ../public/* .
- git add -A .
- git commit -m 'Site updated'
- git branch -m master
- git push -q -u origin master
